### PR TITLE
Create dummy symbol for module initialization for setuptools' Extension class on Windows

### PR DESCRIPTION
**Pull request by nhatbui**
On Windows, setuptools' Extension class must export the symbol
"initlibmgrs" when building the DLL (no way around it). We place dummy
functions in the source to satisfy this. Code has been updated to look
for the DLL (or .pyd in this case), satisfying this for Python 2 and 3.

### CODE REVIEW

**Comment by nhatbui** [comment]
We should discuss the technical debt building up. I know we only want to use a subset of the GeoTrans C library but we're doing a lot of workarounds to avoid having to make all the GeoTrans C code into a package.

**Comment by hobu** [comment]
Please remove the six dependency.

> We should discuss the technical debt building up. I know we only want to use a subset of the GeoTrans C library but we're doing a lot of workarounds to avoid having to make all the GeoTrans C code into a package.

I'm not sure what you mean by technical debt. This library has been around for 5 years, and it only does one thing. A full wrap of GeoTrans, while it might be nice, would be a lot of work. That library's arrangement isn't very convenient to do it either.

**Comment by nhatbui** [comment]
Removed 'six' package dependency.

Regarding my comment on technical debt: sorry if I sounded dramatic. I just wanted to say there may be special cases that break the package like some environments naming our .pyd file differently or saving the .pyd elsewhere. "Finding the .pyd" I'm not so worried about: using sys.path to locate the .pyd is an improvement. Being able to `import libmgrs` would be the bullet-proof solution but yes, that's a lot of work and not the aim of this package.

**Comment by hobu** [comment]
>  I just wanted to say there may be special cases that break the package like some environments naming our .pyd file differently or saving the .pyd elsewhere. "Finding the .pyd" I'm not so worried about: using sys.path to locate the .pyd is an improvement. 

That code was stolen from Shapely from six years ago. I'm happy to merge anything that fixes it up.

**Comment by nhatbui** [comment]
Sounds good. Well, that's my windows fix. Works on Windows 7/8 and 10.

**Pull request merged**
