### PR TITLE
Clean up install vs. build requirements

### PR DESCRIPTION
**Pull request by jwilges**
### Summary

Clean up install vs. build requirements

- Exclude `wheel` and `setuptools` from package dependencies
- Exclude `packaging` from build dependencies; however, retain it as a package
  dependency since it is a valid runtime dependency

### Issue
When downstream packages depend on `mgrs` today, they have `wheel` forced into their dependency graphs at install time.  This occurs because `mgrs` as the upstream package currently lists two of its build requirements--`wheel` and `setuptools`--as install requirements. To clean this up, we can keep `wheel` and `setuptools` as valid build system requirements in `pyproject.toml`, but we should omit them from `setup.py`'s `install_requires` section.

### CODE REVIEW

**Comment by jwilges** [comment]
@hobu let me know if you have any issues with this, but if not, it would be seriously awesome to get this merged and pushed as a newer release on PyPI so we can update our downstream references and shake `wheel` out of our dependency graphs.

**Comment by jwilges** [comment]
You might win the open source hero award for fastest maintainer @hobu... Much love from the PNW, my friend!

I'm working on fixing our dependencies and this one was throwing us for a loop so I wanted to contribute the fix for all to enjoy. I'll keep an eye out for the PyPI version bump once you get a chance to release!

**Comment by hobu** [comment]
github actions borked right now, but when it catches up to the queue, the release will be pushed to PyPI.

**Comment by jwilges** [comment]
Thanks @hobu, it's really appreciated!

**Pull request merged**
